
# this script contains functions to simulate trials

#' @title gen_randomisation
#' @description Generates a randomisation list.
#' @param N Total sample size.
#' @param p_alloc Allocation probabilities for each arm. Must be a vector of values between zero and one, and must sum to one.
#' @param exact Logical. If set to TRUE then the total sample size will be split across the arms according to the proportions defined by p_alloc (equivalent to a blocked design). If set to FALSE then allocations are generated dynamically (i.e., without blocking) and risks imbalance.
#' @return Vector of arm allocations of length N.
#' @examples
#' N <- 1000
#' p_alloc <- c(0.5, 0.5)
#'
#' rand_exact <- gen_randomisation(N, p_alloc, exact = TRUE)
#' table(rand_exact)
#'
#' rand_inexact <- gen_randomisation(N, p_alloc, exact = FALSE)
#' table(rand_inexact)
#' @rdname gen_randomisation
#' @export
gen_randomisation <- function(N, p_alloc, exact){
  if(sum(p_alloc) != 1 | !all(p_alloc >= 0 & p_alloc <= 1)) stop("p_alloc must be a vector of values between zero and one and must sum to one.")
  if(exact){
    alloc <- floor(N*p_alloc)
    remainder <- N - sum(alloc)
    if(remainder > 0) alloc[seq_len(remainder)] <- alloc[seq_len(remainder)] + 1
    rand <- sample(rep(1:length(p_alloc), times = alloc))
  } else {
    rand <- sample(1:length(p_alloc), size = N, replace = TRUE, prob = p_alloc)
  }
  return(rand)
}

#' @title gen_outcomes
#' @description Generates Bernoulli outcome data.
#' @param rand Randomisation list generated by gen_randomisation().
#' @param p_k Vector of outcome probabilities for each arm. Values must be between zero and one.
#' @return Vector of outcomes of equal length to rand.
#' @examples
#' N <- 1000
#' p_alloc <- c(0.5, 0.5)
#' rand <- gen_randomisation(N, p_alloc, exact = TRUE)
#' p_k <- c(0.2, 0.3)
#'
#' out <- gen_outcomes(rand, p_k)
#' prop.table(table(rand, out), 1)
#' @rdname gen_outcomes
#' @export
gen_outcomes <- function(rand, p_k){
  if(!all(p_k >= 0 & p_k <= 1)) stop("p_k must be a vector of values between zero and one.")
  rbinom(n = length(rand), size = 1, prob = p_k[rand])
}

#' @title upt_posterior
#' @description Updates a Beta-Binomial posterior distribution.
#' @param pars Current set of hyperparameters (usually from the prior distribution). Must be a matrix with rows for the hyperparameters "a" and "b", and columns for the arms.
#' @param rand Randomisation list generated by gen_randomisation().
#' @param out Vector of outcomes generatedby gen_outcomes().
#' @return Matrix of updated hyperparameters with the same dimension names as the input hyperparameters.
#' @examples
#' pars <- matrix(rep(1, 4), nrow = 2, ncol = 2, dimnames = list(c("a", "b"), c("NS", "MV")))
#' N <- 1000
#' p_alloc <- c(0.5, 0.5)
#' rand <- gen_randomisation(N, p_alloc, exact = TRUE)
#' p_k <- c(0.2, 0.3)
#' out <- gen_outcomes(rand, p_k)
#'
#' upt_posterior(pars, rand, out)
#' @rdname upt_posterior
#' @export
upt_posterior <- function(pars, rand, out){
  pars_upt <- sapply(1:ncol(pars), function(k) c(pars["a", k] + sum(out[rand == k]), pars["b", k] + sum(rand == k) - sum(out[rand == k])))
  dimnames(pars_upt) <- dimnames(pars)
  return(pars_upt)
}

#' @title sim_trial
#' @description Simulates a trial by generating a randomisation list, generating the outcomes and updating the Beta-Binomial posterior distribution.
#' @param N Total sample size.
#' @param p_alloc Allocation probabilities for each arm. Must be a vector of values between zero and one, and must sum to one.
#' @param p_k Vector of outcome probabilities for each arm. Values must be between zero and one.
#' @param priors Prior distribution hyperparameters. Must be a matrix with rows for the hyperparameters "a" and "b", and columns for the arms.
#' @param exact Logical. If set to TRUE then the total sample size will be split across the arms according to the proportions defined by p_alloc (equivalent to a blocked design). If set to FALSE then allocations are generated dynamically (i.e., without blocking) and risks imbalance. Default is TRUE.
#' @return Matrix of updated hyperparameters with the same dimension names as the input priors.
#' @examples
#' N <- 1000
#' p_alloc <- c(0.5, 0.5)
#' p_k <- c(0.2, 0.3)
#' priors <- matrix(rep(1, 4), nrow = 2, ncol = 2, dimnames = list(c("a", "b"), c("NS", "MV")))
#'
#' sim_trial(N, p_alloc, p_k, priors)
#' @rdname sim_trial
#' @export
sim_trial <- function(N, p_alloc, p_k, priors, exact = TRUE){
  rand <- gen_randomisation(N = N, p_alloc = p_alloc, exact = exact)
  out <- gen_outcomes(rand = rand, p_k = p_k)
  pars <- upt_posterior(pars = priors, rand = rand, out = out)
  return(pars)
}

#' @title draw_beta
#' @description Draws samples from the Beta distribution given a set of hyperparameters.
#' @param pars Matrix of hyperparameters with rows for the hyperparameters "a" and "b", and columns for the arms.
#' @param N_draw Number of samples to draw.
#' @return Matrix containing N_draw samples drawn (rows) for each arm (columns).
#' @examples
#' pars <- matrix(c(1, 2, 1, 3), nrow = 2, ncol = 2, dimnames = list(c("a", "b"), c("NS", "MV")))
#' N_draw <- 10000
#'
#' draws <- draw_beta(pars, N_draw)
#' colMeans(draws)
#' @rdname draw_beta
#' @export
draw_beta <- function(pars, N_draw) apply(pars, 2, function(arm_pars) rbeta(N_draw, arm_pars["a"], arm_pars["b"]))

#' @title gen_eff_distributions
#' @description Generates uncertainty distributions for the strategy effectiveness parameters.
#' @param pars Matrix of hyperparameters with rows for the hyperparameters "a" and "b", and columns for the arms.
#' @param N_draw Number of samples to draw. Default is 10,000.
#' @return Matrix containing N_draw samples drawn (rows) for each arm (columns).
#' @examples
#' pars <- matrix(c(2, 1, 1, 2, 1, 5), nrow = 2, ncol = 3, dimnames = list(c("a", "b"), c("NS", "MV", "IM")))
#'
#' draws <- gen_eff_distributions(pars)
#' colMeans(draws)
#' @rdname gen_eff_distributions
#' @export
gen_eff_distributions <- function(pars, N_draw = 10000){
  p_k <- draw_beta(pars = pars, N_draw = N_draw)
  cbind(MV = 1 - p_k[,"MV"]/p_k[,"NS"],
        IM = 1 - p_k[,"IM"]/p_k[,"NS"])
}

